# 背景颜色
background: '#184e6388'

#导航菜单
menu:
  主页: / || fas fa-home
  博客||fas fa-folder-open:
    归档: /archives/ || fas fa-archive
    分类: /categories/ || fas fa-folder-open
  工具: /tools/ || fas fa-tools
  列表||fas fa-list:
    音乐: /music/ || fas fa-music
    电影: /movies/ || fas fa-video
  友情链接: /link/ || fas fa-link
  关于: /about/ || fas fa-heart
  # 更多: /more/ || fas fa-list

# 副标题
subtitle:
  enable: true
  effect: true # 开启打字效果
  loop: true # 循环打字
  # source調用第三方服務                                   ((貌似没用))
  # source: false 關閉調用
  # source: 1  調用搏天api的隨機語錄（簡體）
  # source: 2  調用一言網的一句話（簡體）
  # source: 3  調用一句網（簡體）
  # source: 4  調用今日詩詞（簡體）
  # subtitle 會先顯示 source , 再顯示 sub 的內容
  source: false
  # 如果有英文逗号' , ',请使用转义字元 &#44;
  # 如果有英文双引号' " ',请使用转义字元 &quot;
  # 开头不允許转义字元，如需要，请把整個句子用双引号包住
  # 如果关闭打字效果，subtitle只会现示sub的第一行文字
  sub:
    - 有人星夜赴科举，有人辞官归故里。


# 侧边栏
aside: 
  enable: true
  hide: false
  mobile: true # 移动设备显示
  position: left # 位置放在左边
  card_author: # 博客主人卡片
    enable: true
    description: '欢迎光临~我会在这里分享技术和一些见解。' # 顶替_config.yml里的description内容
    button: # 那个followGitHub的按钮
      enable: false
  card_announcement: #公告卡片
    enable: true
    content: 这是我的博客！有疑问欢迎联系我提出！
    
# 鼠标点击效果
click_heart: # 点击出现爱心
  enable: true
  mobile: true


# 图像
# 网站图标
# favicon: /img/icon.ico
# 头像
avatar:
  img: /img/avatar.jpg
  effect: false 
# 主页封面背景图
index_img: /img/cover/wall.jpg
# 文章页默认顶部图
default_top_img: /img/cover/wall.jpg
# 归档页顶部图
archive_img: /img/cover/wall.jpg

# 代码
highlight_shrink: false # false为默认展开
# 代码换行(好像没用)
# code_word_wrap: true
highlight_theme: mac
highlight_copy: true #显示复制按钮
highlight_lang: true #显示代码块的语言

# 评论
comments:
  # Up to two comments system, the first will be shown as default
  # Choose: Disqus/Disqusjs/Livere/Gitalk/Valine/Waline/Utterances/Facebook Comments/Twikoo
  use: Twikoo
  text: true # 是否显示评论服务商的名字 Display the comment name next to the button
  # lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: true #false #是否为评论开启lazyload，开启后，只有滚动到评论位置时才会加载评论所需要的资源（开启lazyload后，评论数将不显示）
  count: true #false # 是否在文章顶部显示评论数 Display comment count in post's top_img
  card_post_count: true #false # 是否在首页文章卡片显示评论数 Display comment count in Home Page


# Twikoo 评论
# https://github.com/imaegoo/twikoo
twikoo:
  envId: https://williamrjw-twikoo.vercel.app/ #环境地址
  region:
  visitor: true #false # 是否显示文章阅读数
  option:

# 赞赏
reward:
  enable: true
  QR_code:
    - img: img/wechat.png
      link:
      text: 微信
    # - img: 
    #   link:
    #   text: 支付宝


# 社交
social:
  fab fa-github: https://github.com/Williamrjw || Github
  fa fa-rss-square: /atom.xml || RSS
  fas fa-envelope: mailto:Williamrjw@yeah.net || Email

# 搜索
local_search:
  enable: true


# 数学
# --------------------------------------
# About the per_page
# if you set it to true, it will load mathjax/katex script in each page (true 表示每一頁都加載js)
# if you set it to false, it will load mathjax/katex script according to your setting (add the 'mathjax: true' in page's front-matter)
# (false 需要時加載，須在使用的 Markdown Front-matter 加上 mathjax: true)

# MathJax
mathjax:
  enable: false
  per_page: false

# KaTeX
katex:
  enable: false
  per_page: false
  hide_scrollbar: true